#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"

echo "Running Schemathesis directly"
echo "To run using pytest run the command 'uv run pytest'"
echo

cd "$PROJECT_DIR/tests"
uv run schemathesis run http://localhost:8000/openapi.json
